### ISSUE TITLE
How do I actually use the scripts

### ISSUE THREAD

**Issue by MEGA-Dawg68** [dithpri/RCES#8]
Very cool program but I want to know how do I start the NsIssueOpener, NsIssueCompactorRand and NsDilemmaAutoClose. Is there a certain tool I need to use? Like an extension? Or an app?

**Comment by dithpri** [comment]
A userscript manager, like [Violentmonkey](https://addons.mozilla.org/en-US/firefox/addon/violentmonkey/) or [Tampermonkey](https://addons.mozilla.org/en-US/firefox/addon/tampermonkey/)

**Comment by MEGA-Dawg68** [comment]
Works amazing thank you so much!
One thing is when I have completed the last issue it will close the website stopping me from just entering another nation. is there anyway to stop that?

**Comment by dithpri** [comment]
You can remove the line with `window.close()` in the script source(s). Based on your description, you probably want to remove it from `NsIssueOpener`
